src/apis/auth/auth.ts, src/apis/auth/refresh.ts, src/apis/clients/appClient.ts, src/app/page.tsx, src/components/login/loginForm.tsx, src/components/ui/alert.tsx
- access token session에 저장
- axios요청 헤더에 content-type 삭제
- refreshToken으로 accessToken 재발행 기능구현
- axios 인터셉터 기능 구현
- refreshToken만료 시 로그인페이지로 이동
=> feat: login API 연동

src/components/board/question/QnaSelectFacultyModal.tsx, src/components/common/BottomSheetModal.tsx, src/components/common/SubmitFormBtn.tsx
바텀시트 하단 폼제출 버튼 구현
바텀시트 내 코드 수정-> api통신 기능하는 onSubmit 추가
=> feat(바텀시트): 바텀시트 하단 폼제출 버튼 구현

src/app/board/question/page.tsx, src/components/board/question/QnaFilterFacultyCategory.tsx, src/components/board/question/QnaSelectFacultyModal.tsx, src/components/common/BottomSheetModal.tsx
**바텀시트 하단 폼제출 버튼 수정**
바텀시트 내 코드 수정-> api통신 기능하는 onSubmit 삭제
#39 참고
=> feat(질문게시판): 학과선택 필터링 바텀시트 수정

src/apis/question/getCategoryQNAs.ts, src/app/board/question/detail/[id]/page.tsx, src/app/board/question/page.tsx, src/components/board/tags/ChaeTakTag.tsx, src/components/common/LoadingSpinner.tsx, src/components/common/Pagination.tsx
- [feat(질문게시판): 질문게시판 페이지네이션 기능 구현]
- [feat(질문게시판): 로딩 시 LoadingSpinner 추가]
=> feat(질문게시판): 질문게시판 페이지네이션 기능 구현

src/app/board/question/page.tsx, src/app/board/question/post/page.tsx, src/components/board/question/post/formInput/ContentInput.tsx, src/components/board/question/post/formInput/CustomTagsInput.tsx, src/components/board/question/post/formInput/FileUploadInput.tsx, src/components/board/question/post/formInput/JijeongTagInput.tsx, src/components/board/question/post/formInput/PrivateSettingInput.tsx, src/components/board/question/post/formInput/SubjectSearchInputComponent.tsx, src/components/board/question/post/formInput/TitleInput.tsx, src/components/board/question/post/formInput/YeopjeonRewardInput.tsx, src/components/nav/QnaPostNav.tsx
feat(질문글등록): 임시저장 기능 구현
refactor(질문글등록): 컴포넌트 분리
=> feat(질문글등록): 임시저장 기능 구현, 컴포넌트 분리

src/apis/member/getAccessInfo.ts, src/components/board/question/QuestionCard.tsx, src/components/board/question/QuestionCardList.tsx, src/components/board/tags/SubjectTag.tsx
<이슈번호>
#316 
#176 
#318 
[feat: 자료게시판 권한 api 엔드포인트 수정](https://github.com/Sejong-Balsamic/Malsami-FE/commit/9cb1ab4de750a1f89c2ba50686c1ece95b0a7bc2)
[feat(질문): 질문 메인 카드 UI 수정](https://github.com/Sejong-Balsamic/Malsami-FE/commit/6cb91976dc4641463da800b547faee19f9e67c64)
=> feat(질문): 질문 메인 카드 UI 수정

src/apis/document/fileDownload.ts, src/components/board/document/detail/DownloadCheckModal.tsx, src/components/board/document/detail/DownloadSuccessModal.tsx
=> fix: doc detail refresh 제거

src/components/common/UploadFAB.tsx, src/components/landing/AllDocument.tsx, src/components/landing/AllQuestion.tsx, src/components/landing/HotDocument.tsx, src/components/landing/HotQuestion.tsx
=> Feat/sbf 30  landing api

src/app/page.tsx, src/components/landing/AllDocument.tsx, src/components/landing/AllQuestion.tsx
=> feat: 랜딩 전체 게시판 특정 게시물 접근 구현

src/app/help/page.tsx, src/app/notice/page.tsx, src/components/nav/LandingNav.tsx, src/components/nav/NoticeHelpNav.tsx
=> fix: /notice /help 폴더위치변경

src/components/nav/DDetailNav.tsx, src/components/nav/QDetailNav.tsx
=> fix: 상세페이지 뒤로가기 버튼 연결 수정

src/app/mypage/page.tsx, src/components/mypage/Facility.tsx
=> fix: 마이페이지에서 페이지 연결 수정

src/app/board/question/detail/[id]/answer/page.tsx
=> feat(질문답변등록): alert창 toast 교체, loadingSpinner 추가

src/app/board/document/page.tsx, src/app/board/question/page.tsx, src/components/common/Pagination.tsx, src/components/common/UploadDocFAB.tsx, src/components/common/UploadQFAB.tsx, src/components/search/result/SearchResultNav.tsx
#327 
[feat(페이지네이션): 페이지네이션 css 수정](https://github.com/Sejong-Balsamic/Malsami-FE/commit/3614eaa5f87761ba6800a5f290f253d43dd28004)
[fix(글등록FAB): 질문/자료게시판 FAB버튼이 페이지네이션 위에서 눌리는 버그 수정](https://github.com/Sejong-Balsamic/Malsami-FE/commit/b7dbf26ee2e086c3ec9d6034a80643860f378f2e)
=> feat(페이지네이션): 페이지네이션 css 수정

src/app/page.tsx, src/components/landing/FlyingBooks.tsx
=> feat(이스터에그): 로그아웃 시 엽전보상 이스터에그 버그 수정

.github/workflows/MALSAMI-FE-EPIC-PR-CI.yaml
=> 현재 프론트엔드 프로젝트 구조 개선

src/app/mypage/page.tsx
=> 마이페이지 경험치 엽전 보이지 않는 버그

src/app/board/question/page.tsx, src/app/search/[query]/page.tsx, src/components/common/Card.tsx, src/components/common/CardList.tsx, src/components/common/LandingCardList.tsx, src/components/common/QuestionCard.tsx, src/components/common/deprecated/CategoryCardList.tsx, src/components/common/tags/PresetTag.tsx, src/components/documentMain/DocCard.tsx, src/components/documentMain/DocFilterControlBar.tsx, src/components/documentMain/DocRequestFilterControlBar.tsx, src/components/landing/MovingCardQuestion.tsx, src/components/questionDetail/QnaDetail.tsx, src/components/questionMain/QnaFilterControlBar.tsx, src/components/questionMain/QnaMovingCard.tsx, src/components/questionMain/QuestionCardList.tsx, src/components/search/SearchQnaContainer.tsx, src/types/api/constants/questionPresetTag.ts
=> 기능요청 card공용컴포넌트 카드리스트 구현

.github/workflows/PROJECT-CI.yaml
=> 카드섹션 부분 헤더 구현하기

src/components/common/FABs/LandingWriteFAB.tsx, src/components/common/FABs/UploadDocumentFAB.tsx, src/components/common/FABs/UploadFAB.tsx, src/components/common/FABs/UploadLandingFAB.tsx, src/components/common/FABs/UploadQuestionFAB.tsx
=> 랜딩 플로팅 버튼 클릭시 헤더 blur 처리안되는 현상
